steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "southamerica-east1-docker.pkg.dev/rachaai-01/app/rachaai-git:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "southamerica-east1-docker.pkg.dev/rachaai-01/app/rachaai-git:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "rachaai-git"
      - "--image"
      - "southamerica-east1-docker.pkg.dev/rachaai-01/app/rachaai-git:$COMMIT_SHA"
      - "--region"
      - "southamerica-east1"
      - "--platform"
      - "managed"